name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 120
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=11wae7OcZGed_7ikIljI99Px0o6919C-m&export=download&confirm=t&uuid=c53f14ff-0451-4762-be47-fb59f6f038d2" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
